packages:
  - packages/*

overrides:
  is-core-module: npm:@nolyfill/is-core-module@^1
  safer-buffer: npm:@nolyfill/safer-buffer@^1
catalog:
  '@biomejs/biome': ^2.2.2
  '@faker-js/faker': ^10.0.0
  '@jhqn/eslint-config': ^0.10.0
  '@types/crypto-js': ^4.2.2
  '@types/node': ^22.15.3
  '@vitest/coverage-v8': ^3.2.4
  '@vueuse/core': ^13.7.0
  '@vueuse/shared': ^13.7.0
  bumpp: ^10.2.3
  crypto-js: ^4.2.0
  dayjs: ^1.11.13
  detect-browser: ^5.3.0
  eslint: ^9.34.0
  eslint-plugin-oxlint: ^1.12.0
  jotai: ^2.13.1
  jsdom: ^26.1.0
  lint-staged: ^16.1.5
  msw: ^2.10.5
  nanoid: ^5.1.5
  npm-run-all2: ^8.0.4
  oxlint: ^1.12.0
  publint: ^0.3.12
  simple-git-hooks: ^2.13.1
  tsdown: ^0.15.0
  typescript: ^5.9.2
  vite: ^7.1.3
  vitest: ^3.2.4

cleanupUnusedCatalogs: true

onlyBuiltDependencies:
  - msw
