packages:
  - packages/*

overrides:
  is-core-module: npm:@nolyfill/is-core-module@^1
  safer-buffer: npm:@nolyfill/safer-buffer@^1
catalog:
  '@faker-js/faker': ^10.4.0
  '@jhqn/eslint-config': ^0.15.0
  '@types/crypto-js': ^4.2.2
  '@types/node': ^24.11.0
  '@vitest/coverage-v8': ^4.1.6
  '@vueuse/core': ^14.3.0
  bumpp: ^11.1.0
  crypto-js: ^4.2.0
  dayjs: ^1.11.20
  detect-browser-es: 0.1.1
  eslint: ^10.3.0
  eslint-plugin-oxlint: ^1.64.0
  jotai: ^2.20.0
  jsdom: ^29.1.1
  lint-staged: ^17.0.4
  msw: ^2.14.6
  nanoid: ^5.1.11
  npm-run-all2: ^8.0.4
  oxfmt: ^0.49.0
  oxlint: ^1.64.0
  publint: ^0.3.21
  simple-git-hooks: ^2.13.1
  tsdown: ^0.22.0
  typescript: ^6.0.3
  vite: ^8.0.13
  vitest: ^4.1.6
  vue: ^3.5.34

cleanupUnusedCatalogs: true

dedupeDirectDeps: true

dedupePeers: true

dedupePeerDependents: true

onlyBuiltDependencies:
  - msw

allowBuilds:
  esbuild: false
  msw: false
  simple-git-hooks: false
  unrs-resolver: false
